# All recipes are for two servings unless specified otherwise.

general_taos_chicken:
  description: A popular Chinese-American dish featuring crispy chicken pieces, red pepper and onion in a sweet and sour sauce.
  ingredients:
    chicken_thighs:
      amount: 300
      unit: grams
    red_pepper:
      amount: 1
      unit: whole
    onion:
      amount: 1
      unit: whole
    cashew:
      amount: 50 # TODO: check for real amount
      unit: grams

  seasoning:
    - soy_sauce
    - rice_vinegar
    - sugar
    - ketchup
    - cornstarch
  # instructions:
  # TODO: add this later

teriyaki_chicken:
  description: A Japanese dish of grilled chicken glazed with a sweet soy sauce-based marinade.
  ingredients:
    chicken_thighs:
      amount: 300
      unit: grams
    garlic:
      amount: 4
      unit: cloves

  seasoning:
    - soy_sauce
    - oyster_sauce
    - sugar

